# 配置文件的键名命名方式统一使用小驼峰。

# HTTP Server.
server:
  address:             ":8199"
  serverRoot:          "resource/public"
  dumpRouterMap:       true
  routeOverWrite:      true
  accessLogEnabled:    false
  accessLogPattern:    "access-{Ymd}.log"
  sessionPath:         "temp/sessions"    # Session文件存储目录
  openapiPath:         "/api.json"
  swaggerPath:         "/swagger"

# 数据库连接配置
database:
  logger:
    path:    "temp/logs/sql"
    level:   "all"
    stdout:  true
    ctxKeys: ["RequestId"]

  default:
    link:   "mysql:root:123456@tcp(127.0.0.1:3306)/go_blog?loc=Local&parseTime=true&charset=utf8mb4"
    # link:   "sqlite::@file(manifest/document/sqlite/focus.db)"
    debug:  true

# 内容设置
setting:
  title:       "cqq.me"
  keywords:    "golang,开发者,php"
  description: ""
  adminIds:    [1] # 管理员ID
  domain:       "local.cqq.me"

# 文件上传设置
upload:
  path: "temp/upload"

# Logger configurations.
logger:
  path:    "temp/logs/default"
  level:   "all"
  stdout:  true
  ctxKeys: ["RequestId"]

# 模板引擎配置
viewer:
  indexLayout:     "index/index.html"
  adminHomeLayout: "admin/home.html"
  adminLayout:     "admin/index.html"

