
# 工具相关配置
gfcli:
  # 工具编译配置
  build:
    name:     "go_blog"
    path:     "./dist"
    arch:     "amd64"
    system:   "linux,darwin,windows"
    mod:      ""
    cgo:      0
    packSrc:   "resource/public,resource/template"

  # dao生成
  gen:
    dao:
      - link:            "mysql:root:123456@tcp(127.0.0.1:3306)/go_blog"
        removePrefix:    "gf_"
        descriptionTag:  true
        noModelComment:  true
